### ISSUE TITLE
Please remove UniMerge assets

### ISSUE THREAD

**Issue by mtschoen** [dhaggerfin/Its_Hip_To_Be_A_Square#1]
Hello there.

I am the author of UniMerge, and I have a google alert on it, which brought me here. UniMerge is a paid license which you do not have permission to redistribute. Please remove it from your repository and follow these steps to remove it from your history:

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

I'm sure this was a mistake, and these things happen. I do not plan to take any legal action or anything of the sort. I just want to make sure that people can't (quite so easily) go get UniMerge for free. If you really want to have it in your repository, please host it privately, or include UniMerge as a submodule, hosted privately.

Also, I'm in the middle of a major update to the tool, so stay tuned! Thanks for your purchase. :)

**Comment by dhaggerfin** [comment]
Hi Matt,

Sorry about that!   I have removed it from our GitHub project.   Long-term we will be moving to a private repo so this won't happen again with yours or other assets!  When we started the project we discussed which repo to go for and thought that since we arent building a commercial project that it was fine to host on GitHub.    I didn't even think about the implication of adding paid assets.   Thanks for the heads up and thanks for making UniMerge!

If I haven't done something proper and you can still see the asset in any form please let me know!

David

**Comment by mtschoen** [comment]
Hey David,

Sorry to be a stickler, but just creating a commit where you delete the files isn't enough. It's still in the history. The link I put in my original comment contains the instructions for how to remove the files from history, but I've done this for you in my fork:

https://github.com/mtschoen/Its_Hip_To_Be_A_Square

If you force-pull master from here and force-push back to GitHub, you will successfully remove the files from the history.  I recommend that you test your project and inspect the changes closely. I only removed the Assets/UniMerge folder, but I can't guarantee that the BFG tool did it's job properly, and I don't want to be responsible for breaking your project.

I'll check back in a few days to make sure this is done. Thanks for complying with my request. Cheers!
